name: Scala CI + SonarScan

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read
  security-events: write

jobs:
  check_formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - uses: sbt/setup-sbt@v1

      - name: Check code formatting
        run: sbt scalafmtCheckAll

  build_and_test:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest
    needs: check_formatting

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - uses: sbt/setup-sbt@v1

      - name: Compile
        run: sbt compile

      - name: Run tests with coverage
        run: sbt clean coverage test

      - name: Generate coverage report and upload to Coveralls
        run: sbt coverageReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scoverage-report
          path: target/scala-3.7.3/scoverage-report

  sonar_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'adopt'

      - uses: sbt/setup-sbt@v1

      - name: Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: scoverage-report
          path: target/scala-3.7.3/scoverage-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
